-- NOTE: Do not edit this file manually.  It's generated by the build task

-- !Table

{
  "name": "doc_doc_1",
  "fields": {
    "id": {
      "type": "nanoid"
    },
    "rev": {
      "type": "integer",
      "init": 0
    },
    "state": {
      "type": "string",
      "length": 100,
      "init": "new"
    },
    "options": {
      "type": "json"
    },
    "created": {
      "type": "timestamp"
    },
    "modified": {
      "type": "timestamp"
    },
    "deleted": {
      "type": "boolean",
      "init": false
    }
  },
  "indecies": {
    "id": {
      "unique": true
    },
    "state": {},
    "options": {
      "gin": true
    },
    "created": {},
    "modified": {}
  }
}

-- !Downs

DROP TABLE IF EXISTS public.doc_doc_1;

-- !Ups

DO $$ BEGIN IF NOT EXISTS (SELECT * FROM pg_proc WHERE proname = 'moddatetime') THEN CREATE EXTENSION moddatetime; END IF; END; $$;

CREATE TABLE public.doc_doc_1 (
  id CHAR(21) NOT NULL,
  rev INTEGER NOT NULL DEFAULT 0,
  state VARCHAR(100) NOT NULL DEFAULT 'new',
  options JSONB NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  modified TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TRIGGER mdt_moddatetime BEFORE UPDATE ON public.doc_doc_1 FOR EACH ROW EXECUTE PROCEDURE moddatetime (modified);

CREATE UNIQUE INDEX ON public.doc_doc_1 (id);

CREATE INDEX ON public.doc_doc_1 (state);

CREATE INDEX ON public.doc_doc_1 USING GIN(options);

CREATE INDEX ON public.doc_doc_1 (created);

CREATE INDEX ON public.doc_doc_1 (modified);