// NOTE: Do not edit this file manually.  It's generated by the build task

export default {
  docs: {
    'doc.Doc4Rights': {
      rights: require('../model.test/docs/Doc4Rights/rights.js'),
      access: require('../model.test/docs/Doc4Rights/access.js').default,
    },
  },
  rights: require('../model.test/rights'),
  validators: require('../model.test/validators'),
};